name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09

    - name: Install Rust
      uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87
      with:
        components: rustfmt, clippy

    - name: Install cargo-deny
      run: cargo install cargo-deny --locked

    - name: Dependency policy (cargo-deny)
      run: cargo deny check

    - name: Cache cargo registry
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - name: Check Formatting
      run: cargo fmt -- --check

    - name: Run Clippy
      run: cargo clippy -- -D warnings

    - name: Run Tests
      run: cargo test --workspace
